/**
 * Copyright (c) Konstantin Kuzmin. All Rights Reserved.
 * This source code is licensed under the GNU General Public License v3.0
 */

// NOTES
export const NOTE_SELECT = 'NOTE_SELECT';
export const ROOT_SELECT = 'ROOT_SELECT';
export const NOTE_RESET = 'NOTE_RESET';

// QUICK_GUIDE
export const TOGGLE_GUIDE_DISMISSED = 'TOGGLE_GUIDE_DISMISSED';
export const TOGGLE_GUIDE_SHOWN = 'TOGGLE_GUIDE_SHOWN';
export const GUIDE_RESET = 'GUIDE_RESET';

// GUIDE_INDEX
export const GUIDE_INCREMENT = 'GUIDE_INCREMENT';
export const GUIDE_DECREMENT = 'GUIDE_DECREMENT';

// MODE_CARD
export const OPEN_MODE_CARD = 'OPEN_MODE_CARD';
export const CLOSE_MODE_CARD = 'CLOSE_MODE_CARD';

// NAV_DROP_DOWNS
export const TOGGLE_DROP_DOWN = 'TOGGLE_DROP_DOWN';
export const CLOSE_DROP_DOWN = 'CLOSE_DROP_DOWN';

// OVERLAY
export const TOGGLE_KEY_OVERLAY = 'TOGGLE_KEY_OVERLAY';
export const TOGGLE_NOTE_OVERLAY = 'TOGGLE_NOTE_OVERLAY';
export const CLEAR_OVERLAYS = 'CLEAR_OVERLAYS';

// SELECTION_FILTER
export const TOGGLE_SELECTION_FILTER = 'TOGGLE_SELECTION_FILTER';
export const RESET_SELECTION_FILTER = 'RESET_SELECTION_FILTER';

// CLEF
export const CHANGE_CLEF = 'CHANGE_CLEF';
export const RESET_CLEF = 'RESET_CLEF';

// TONALITIES
export const TOGGLE_TONALITY = 'TOGGLE_TONALITY';
export const RESET_TONALITIES = 'RESET_TONALITIES';

// CARDINALITY
export const CHANGE_CARDINALITY = 'CHANGE_CARDINALITY';

// KEYS_ACTIVE
export const CHANGE_KEY_STATE = 'CHANGE_KEY_STATE';
